### PR TITLE
Add class names to both level 1 taxon and sub topics list

### PR DESCRIPTION
**Pull request by fmlharrison**
Add class names so that the design team can add css styling to each list.

https://trello.com/c/qSqKPiNU/56-add-class-to-taxon-lists

### CODE REVIEW

**Comment by vanitabarrett** [comment]
@fmlharrison This is adding classes to the div surrounding each list - is it more useful to be adding the classes to the list HTML elements themselves, e.g: `ul`? 

I may just be lacking context around the work needed here - depends what's most useful for design.

**Comment by fmlharrison** [comment]
@vanitabarrett This could be the case. This is for Mia to be able to as CSS stylings to the lists. I will talk to her to see what she want to be able to do with them.

**Comment by fmlharrison** [comment]
I talked to Mia about this and have decided to add class names to the outer div, ul and li elements.

**Review by vanitabarrett — APPROVED** [review]
When we come to implementing designs, we should probably use BEM for our classes. But for now, this looks good 👍

**Pull request merged**
